CREATE TABLE T_CAMIONES(
    MATRICULA       VARCHAR2(12),
    MODELO          VARCHAR2(50) NOT NULL,
    POTENCIA        NUMBER(5),
    TIPO_SEGURO     VARCHAR2(2),
    TIPO_CAMION     NUMBER(1),
    CONSTRAINT CAMIONES_PK PRIMARY KEY(MATRICULA),
    CONSTRAINT POTENCIA_CHK CHECK (POTENCIA BETWEEN 100 AND 7000),
    CONSTRAINT TIPO_SEGURO_CHK CHECK (TIPO_SEGURO IN ('TR','F1','F2','TE'))
);

CREATE TABLE T_RUTAS(
    MATRICULA_CAMION VARCHAR2(12) NOT NULL,
    FECHA_RUTA DATE NOT NULL,
    NOMBRE_CAMIONERO VARCHAR2(75) NOT NULL,
    ORIGEN_RUTA VARCHAR2(80) NOT NULL,
    DESTINO_RUTA VARCHAR2(80) NOT NULL,
    CONSTRAINT RUTAS_PK PRIMARY KEY(MATRICULA_CAMION, FECHA_RUTA),
    CONSTRAINT RUTAS_MAT_CAM_FK FOREIGN KEY(MATRICULA_CAMION) REFERENCES T_CAMIONES(MATRICULA),
    CONSTRAINT RUTAS_FECHA_RUTA_CHK 
        CHECK(FECHA_RUTA >= TO_DATE('01/01/1980', 'DD/MM/YYYY') 
            AND FECHA_RUTA <= TO_DATE('01/01/2100', 'DD/MM/YYYY'))
);
