--2.1 ELIMINAR NOMBRE CAMIONERO Y AÑADIR APELLIDOS Y NOMBRE EN T_RUTAS
ALTER TABLE T_RUTAS DROP COLUMN NOMBRE_CAMIONERO;
ALTER TABLE T_RUTAS ADD APELLIDO_CAMIONERO VARCHAR2(50) NOT NULL;
ALTER TABLE T_RUTAS ADD NOMBRE_CAMIONERO VARCHAR2(50) NOT NULL;

--2.2 CREAR RESTRICCION TABLA T_CAMIONES (TIPO_CAMION) LLAMADA CL_TIPO_CAMION CON VALORES 1,2,3,4,5
ALTER TABLE T_CAMIONES ADD CONSTRAINT TIPO_CAMION_CHK CHECK (TIPO_CAMION IN (1,2,3,4,5));

--2.3 EN T_CAMIONES INSERTAR COLUMNA LLAMADA ID_CAMION(NUMBER) Y CAMBIAR PK A ID_CAMION
ALTER TABLE T_CAMIONES DROP PRIMARY KEY CASCADE;
ALTER TABLE T_CAMIONES ADD ID_CAMION NUMBER;
ALTER TABLE T_CAMIONES ADD CONSTRAINT PK_CAMIONES PRIMARY KEY(ID_CAMION);

--2.4.1 ELIMINAR PK DE T_RUTAS
ALTER TABLE T_RUTAS DROP PRIMARY KEY;

--2.4.2 ELIMINAR COLUMN MATRICULA Y CREAR COLUMN ID_CAMION(FK T_CAMIONES)
ALTER TABLE T_RUTAS DROP COLUMN MATRICULA_CAMION;
ALTER TABLE T_RUTAS ADD ID_CAMION NUMBER;
ALTER TABLE T_RUTAS ADD CONSTRAINT FK_RUTAS_ID_CAMION FOREIGN KEY(ID_CAMION) REFERENCES T_CAMIONES(ID_CAMION);

--2.4.3 CREAR PK DE T_RUTAS
ALTER TABLE T_RUTAS ADD CONSTRAINT PK_RUTAS PRIMARY KEY(ID_CAMION, FECHA_RUTA);
