--3.1. CREAR USUARIO LLAMADO PRAC1 CON CLAVE 1ASt24, TABLESPACE POR DEFECTO USERS Y TABLESPACE TEMPORAL TEMP
CREATE USER PRAC1 IDENTIFIED BY "1ASt24"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

--3.2 PRAC1 ROLES CONNECT Y RESOURCE Y PRIVILEGIO PARA CREAR VISTAS
GRANT RESOURCE, CONNECT, CREATE VIEW TO PRAC1;