--BORRADO DE TABLAS Y OBJETOS
/*
DROP TABLE SERVICIOS_OBJ;
DROP TABLE CLIENTES_OBJ;
DROP TYPE CLIENTE FORCE;
DROP TYPE SERVICIO FORCE;
DROP TYPE PERSONAL FORCE;
/
*/

--1. CREAR OBJETO PERSONAL
CREATE OR REPLACE TYPE PERSONAL AS OBJECT
(
  IDCLIENTE NUMBER(5),
  DNI VARCHAR2(10),
  NOMBRE VARCHAR2(30),
  CALLE VARCHAR2(100),
  POBLACION VARCHAR2(50),
  PROVINCIA VARCHAR2(30),
  FECHA_ALTA DATE
) NOT FINAL;
/

--2. CREAR  OBJETO CLIENTE QUE HEREDA DE PERSONAL CON DOS CONSTRUCTORES Y FUNCION getDireccion
CREATE OR REPLACE TYPE CLIENTE UNDER PERSONAL (
    NRO_CUENTA VARCHAR2(20),
    TIPO_CLI NUMBER(1),
    --CONSTRUCTOR 1
    CONSTRUCTOR FUNCTION CLIENTE(
        IDCLIENTE NUMBER,
        DNI VARCHAR2,
        NOMBRE VARCHAR2,
        APELLIDOS VARCHAR2,
        CALLE VARCHAR2,
        POBLACION VARCHAR2,
        PROVINCIA VARCHAR2
    ) RETURN SELF AS RESULT,
    --CONSTRUCTOR 2
    CONSTRUCTOR FUNCTION CLIENTE(
        IDCLIENTE NUMBER,
        DNI VARCHAR2,
        NOMBRE VARCHAR2,
        CALLE VARCHAR2,
        POBLACION VARCHAR2,
        PROVINCIA VARCHAR2,
        FECHA_ALTA DATE,
        NRO_CUENTA VARCHAR2,
        TIPO_CLI NUMBER
    )RETURN SELF AS RESULT,
    --FUNCION GETDIRECCION
    MEMBER FUNCTION getDireccion RETURN VARCHAR2
);
/

--BODY
CREATE OR REPLACE TYPE BODY CLIENTE AS
    --CONSTRUCTOR 1
  CONSTRUCTOR FUNCTION CLIENTE(
        IDCLIENTE NUMBER,
        DNI VARCHAR2,
        NOMBRE VARCHAR2,
        APELLIDOS VARCHAR2,
        CALLE VARCHAR2,
        POBLACION VARCHAR2,
        PROVINCIA VARCHAR2
  ) RETURN SELF AS RESULT IS
  BEGIN
    SELF.IDCLIENTE := IDCLIENTE;
    SELF.DNI := DNI;
    SELF.NOMBRE := NOMBRE || ' ' || APELLIDOS;
    SELF.CALLE := CALLE;
    SELF.POBLACION := POBLACION;
    SELF.PROVINCIA := PROVINCIA;
    SELF.FECHA_ALTA := SYSDATE;
    RETURN;
  END CLIENTE;
    --CONSTRUCTOR 2
  CONSTRUCTOR FUNCTION CLIENTE(
        IDCLIENTE NUMBER,
        DNI VARCHAR2,
        NOMBRE VARCHAR2,
        CALLE VARCHAR2,
        POBLACION VARCHAR2,
        PROVINCIA VARCHAR2,
        FECHA_ALTA DATE,
        NRO_CUENTA VARCHAR2,
        TIPO_CLI NUMBER
  ) RETURN SELF AS RESULT IS
  BEGIN
    SELF.IDCLIENTE := IDCLIENTE;
    SELF.DNI := DNI;
    SELF.NOMBRE := NOMBRE;
    SELF.CALLE := CALLE;
    SELF.POBLACION := POBLACION;
    SELF.PROVINCIA := PROVINCIA;
    SELF.FECHA_ALTA := SYSDATE;
    SELF.NRO_CUENTA := NRO_CUENTA;
    SELF.TIPO_CLI := TIPO_CLI;
    RETURN;
  END CLIENTE;
    --FUNCION GETDIRECCION
  MEMBER FUNCTION getDireccion RETURN VARCHAR2 AS
  BEGIN
    RETURN SELF.CALLE || ', ' || SELF.POBLACION || ', ' || SELF.PROVINCIA;
  END getDireccion;
  
END;
/

-- 3. CREAR OBJETO SERVICIO
CREATE OR REPLACE TYPE SERVICIO AS OBJECT (
  IDSERVICIO NUMBER(5),
  REFCLIENTE REF CLIENTE,
  NRO_HORAS NUMBER(3),
  PRECIO_HORA NUMBER(5,2),
  FECHA_SERVICIO DATE
);
/

--4. CREAR TABLA CLIENTES_OBJ DE CLIENTES
CREATE TABLE CLIENTES_OBJ OF CLIENTE (PRIMARY KEY (IDCLIENTE));
/
INSERT INTO CLIENTES_OBJ VALUES(
    CLIENTE(1, '111111111A', 'MAR�A', 'LASO MAR', 'TOLEDO, 21-1� C', 'CIUDAD REAL', 'CIUDAD CIUDAD')
    );
INSERT INTO CLIENTES_OBJ VALUES(
    CLIENTE(2, '2222222B', 'MIRTA GIL, JUAN','COSO,10','DAIMIEL','CIUDAD REAL',TO_DATE('04/02/2021', 'DD/MM/YYYY'),'1234567890',1)
);
INSERT INTO CLIENTES_OBJ VALUES(
    CLIENTE(3, '33333333C', 'TOSAR MESA, PEDRO','BARRIAL,10', 'ARG�S', 'TOLEDO',TO_DATE('03/08/2020', 'DD/MM/YYYY'),'1234567890',1)
);
COMMIT;
/

--5. CREAR TABLA SERVICIOS_OBJ DE SERVICIOS
CREATE TABLE SERVICIOS_OBJ OF SERVICIO;
/

--6. CREAR BLOQUE SQL
DECLARE
    REFCLIENTE1 REF CLIENTE;
    REFCLIENTE2 REF CLIENTE;
    REFCLIENTE3 REF CLIENTE;
    CLIENTE_2 CLIENTE;
    SERVICIO_V SERVICIO;
    
BEGIN
    SELECT REF(c) INTO REFCLIENTE1 FROM CLIENTES_OBJ c WHERE IDCLIENTE = 1;
    SELECT REF(c) INTO REFCLIENTE2 FROM CLIENTES_OBJ c WHERE IDCLIENTE = 2;
    
    INSERT INTO SERVICIOS_OBJ VALUES(11, REFCLIENTE1, 10, 30, TO_DATE('01/02/2022', 'DD/MM/YYYY'));
    INSERT INTO SERVICIOS_OBJ VALUES(22, REFCLIENTE2, 20, 40, TO_DATE('12/03/2022', 'DD/MM/YYYY'));
    --SELECCIONAR DE CLIENTES EL ID 2 Y GUARDARLO EN CLIENTE_2
    select VALUE(c) INTO CLIENTE_2 FROM CLIENTES_OBJ c WHERE IDCLIENTE = 2;
    --CAMBIAR EL IDCLIENTE DE CLIENTE2 a 22
    CLIENTE_2.IDCLIENTE := 22;
    --CAMBIAR el DNI a 21111111B
    CLIENTE_2.DNI := '21111111B';
    --INSERTAR CLIENTE_2 EN CLIENTES_OBJ
    INSERT INTO CLIENTES_OBJ VALUES(CLIENTE_2);
    --SELECCIONAR DE SERVICIOS_OBJ EL ID 11 Y GUARDARLO EN SERVICIO_V
    SELECT VALUE(s) INTO SERVICIO_V FROM SERVICIOS_OBJ s WHERE IDSERVICIO = 11;
    --OBTENER DE CLIENTE LA REFERENCIA ID=3 Y ALMACENARLO EN REFCLIENTE3
    SELECT REF(c) INTO REFCLIENTE1 FROM CLIENTES_OBJ c WHERE IDCLIENTE = 3;
    --MODIFICAR SERVICIO_V A IDSERVICIO=12 Y REFCLIENTE=REFCLIENTE3
    SERVICIO_V.IDSERVICIO := 12;
    SERVICIO_V.REFCLIENTE := REFCLIENTE3;
    --INSERTAR EN SERVICIOS_OBJ EL SERVICIO_V
    INSERT INTO SERVICIOS_OBJ VALUES(SERVICIO_V);
END;
/

--EJERCICIO 7
SELECT s.IDSERVICIO, c.NOMBRE, c.DNI, c.POBLACION, s.NRO_HORAS, s.PRECIO_HORA, (s.NRO_HORAS * s.PRECIO_HORA) AS TOTAL  
FROM SERVICIOS_OBJ s
JOIN CLIENTES_OBJ c ON s.REFCLIENTE.IDCLIENTE = c.IDCLIENTE;